name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v5

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run tests
        run: pnpm test
